version: '3.8'
services:
  app:
    container_name: nova-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - HOST=${HOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
    command: npm run start:dev
